/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { CatalogRisk } from "./types";

export const DEFAULT_RISK_CATALOG: CatalogRisk[] = [
  {
    id: "risk-1",
    name: "Sobrecarga Quantitativa de Trabalho",
    source: "Volume excessivo de tarefas, prazos impraticáveis, quadro de funcionários subdimensionado ou picos sazonais de demanda.",
    possibleInjuries: "Esgotamento profissional (Burnout), estresse crônico, distúrbios do sono, ansiedade geral e fadiga mental acumulada.",
    defaultLevel: "Moderado",
    diseaseHistory: "Nenhum registro oficial de adoecimento até o momento.",
    existingControls: "Distribuição informal de tarefas e compensação eventual de horas extras.",
    probability: 3,
    severity: 3,
    uncertainty: "Certa",
    recommendation: "Redimensionar o quadro de funcionários, revisar metas e estabelecer priorização clara de demandas.",
    priority: "Média",
    responsible: "Liderança e Gestores",
    status: "Pendente",
    deadline: "A definir pela empresa",
    periodicity: "A definir pela empresa",
    monitoring: "Checklists de monitoramento periódico e reuniões semanais de alinhamento de capacidade.",
    measureResults: "Redução de horas extras não planejadas e estabilização dos índices de absenteísmo.",
    actionObjective: "Adequar o volume e os prazos das atividades laborais à capacidade da equipe.",
    actionProposed: "Mapear o fluxo de atividades, redistribuir cargas e instituir protocolo de priorização de demandas.",
    efficacyIndicator: "Índice de horas extras e pontuação da dimensão de demandas no COPSOQ II"
  },
  {
    id: "risk-2",
    name: "Ritmo de Trabalho Acelerado",
    source: "Metas abusivas, cobrança contínua por produtividade imediata, velocidade imposta por máquinas ou esteiras de produção.",
    possibleInjuries: "Lombalgias e dores osteomusculares (DORT/LER), cefaleia de tensão, irritabilidade crônica e episódios de pânico.",
    defaultLevel: "Moderado",
    diseaseHistory: "Nenhum registro oficial de adoecimento até o momento.",
    existingControls: "Pausas informais durante a jornada.",
    probability: 3,
    severity: 3,
    uncertainty: "Certa",
    recommendation: "Implementar pausas regulares programadas e calibrar a cadência operacional de acordo com critérios ergonômicos.",
    priority: "Média",
    responsible: "Supervisão e Segurança do Trabalho",
    status: "Pendente",
    deadline: "A definir pela empresa",
    periodicity: "A definir pela empresa",
    monitoring: "Acompanhamento ergonômico em campo e escuta mensal dos operadores.",
    measureResults: "Diminuição de queixas osteomusculares e relato de ritmo sustentável nas pesquisas.",
    actionObjective: "Promover cadência de trabalho compatível com a higidez física e mental dos trabalhadores.",
    actionProposed: "Definir pausas ergonômicas de 10 minutos a cada turno e revisar metas de velocidade.",
    efficacyIndicator: "Relatório de queixas ambulatoriais e avaliação ergonômica preliminar"
  },
  {
    id: "risk-3",
    name: "Falta de Autonomia e Controle",
    source: "Processos extremamente rígidos com decisões centralizadas, ausência de voz ativa na organização do próprio tempo de trabalho.",
    possibleInjuries: "Sentimento de desvalorização profissional, desmotivação profunda, sintomas depressivos leves ou moderados.",
    defaultLevel: "Baixo",
    diseaseHistory: "Nenhum registro oficial de adoecimento até o momento.",
    existingControls: "Reuniões periódicas da equipe.",
    probability: 2,
    severity: 2,
    uncertainty: "Certa",
    recommendation: "Conceder margem de manobra na execução de rotinas e envolver os colaboradores no planejamento setorial.",
    priority: "Baixa",
    responsible: "Gestão de Recursos Humanos e Chefias Imediatas",
    status: "Pendente",
    deadline: "A definir pela empresa",
    periodicity: "A definir pela empresa",
    monitoring: "Espaços regulares de escuta e avaliação de sugestões de melhoria.",
    measureResults: "Aumento do engajamento e melhoria na pontuação de influência e desenvolvimento.",
    actionObjective: "Ampliar a participação e a autonomia decisória dos colaboradores em suas rotinas.",
    actionProposed: "Instituir fóruns mensais de melhoria contínua e flexibilidade na ordenação das tarefas diárias.",
    efficacyIndicator: "Índice de retenção de talentos e escore da dimensão Influência no COPSOQ II"
  },
  {
    id: "risk-4",
    name: "Apoio Social Insuficiente (Chefia/Colegas)",
    source: "Liderança autocrática, falta de feedback construtivo, clima organizacional competitivo ou isolamento físico/virtual das equipes.",
    possibleInjuries: "Isolamento social no trabalho, desânimo, ansiedade e dificuldade de comunicação interpessoal.",
    defaultLevel: "Moderado",
    diseaseHistory: "Nenhum registro oficial de adoecimento até o momento.",
    existingControls: "Canais de comunicação formal corporativa.",
    probability: 3,
    severity: 3,
    uncertainty: "Certa",
    recommendation: "Capacitar a liderança em gestão humanizada e promover práticas de feedback estruturado contínuo.",
    priority: "Média",
    responsible: "Recursos Humanos e Diretoria Operacional",
    status: "Pendente",
    deadline: "A definir pela empresa",
    periodicity: "A definir pela empresa",
    monitoring: "Pesquisa de clima organizacional e registros de feedbacks 1:1.",
    measureResults: "Melhoria sensível das relações interpessoais e redução de conflitos internos.",
    actionObjective: "Fortalecer o apoio social e a integração colaborativa entre gestores e liderados.",
    actionProposed: "Treinar supervisores em comunicação não violenta e realizar reuniões de alinhamento quinzenais.",
    efficacyIndicator: "Pesquisa de Clima Organizacional e índice da dimensão Relações Interpessoais"
  },
  {
    id: "risk-5",
    name: "Conflito de Papéis e Ambiguidade",
    source: "Ausência de definição clara de cargos e funções, acúmulo informal de tarefas conflitantes ou ordens contraditórias de diferentes líderes.",
    possibleInjuries: "Tensão constante por insegurança ocupacional, estresse elevado, baixa autoeficácia laboral.",
    defaultLevel: "Moderado",
    diseaseHistory: "Nenhum registro oficial de adoecimento até o momento.",
    existingControls: "Descrições resumidas de cargos no momento da contratação.",
    probability: 3,
    severity: 3,
    uncertainty: "Certa",
    recommendation: "Elaborar organograma claro, descritivos de função atualizados e matriz de responsabilidade (RACI).",
    priority: "Média",
    responsible: "Recursos Humanos e Coordenação Setorial",
    status: "Pendente",
    deadline: "A definir pela empresa",
    periodicity: "A definir pela empresa",
    monitoring: "Revisão semestral dos descritivos e alinhamento com a liderança.",
    measureResults: "Eliminação de sobreposições de comando e segurança nas entregas.",
    actionObjective: "Garantir clareza de papel laboral e alinhamento de expectativas para cada função.",
    actionProposed: "Publicar matriz de responsabilidades e formalizar linhas de reporte hierárquico.",
    efficacyIndicator: "Escore de clareza de papel no COPSOQ II e taxa de retrabalho"
  },
  {
    id: "risk-6",
    name: "Conflito Trabalho-Família (Dupla Jornada)",
    source: "Horas extras habituais não planejadas, escalas de revezamento instáveis ou chamados de trabalho fora do horário de expediente.",
    possibleInjuries: "Desgaste nas relações sociofamiliares, cansaço extremo físico e mental, sentimento de culpa crônica.",
    defaultLevel: "Moderado",
    diseaseHistory: "Nenhum registro oficial de adoecimento até o momento.",
    existingControls: "Controle de ponto eletrônico.",
    probability: 3,
    severity: 3,
    uncertainty: "Certa",
    recommendation: "Respeitar rigorosamente o direito à desconexão e planejar escalas com antecedência mínima de 15 dias.",
    priority: "Média",
    responsible: "Liderança Direta e Departamento Pessoal",
    status: "Pendente",
    deadline: "A definir pela empresa",
    periodicity: "A definir pela empresa",
    monitoring: "Relatórios de acionamento fora do expediente e horas de trabalho registradas.",
    measureResults: "Redução a zero de mensagens/ligações corporativas fora do horário de jornada.",
    actionObjective: "Preservar os períodos de descanso e convivência sociofamiliar dos colaboradores.",
    actionProposed: "Instituir política de desconexão digital fora do expediente e limitar horas suplementares.",
    efficacyIndicator: "Auditoria de ponto e escore na dimensão Conflitos Família-Trabalho"
  },
  {
    id: "risk-7",
    name: "Insegurança quanto ao Vínculo de Trabalho",
    source: "Ameaça frequente de demissão, instabilidade financeira do setor, falta de plano de carreira ou contratos temporários recorrentes.",
    possibleInjuries: "Ansiedade crônica antecipatória, insônia, medo de manifestar opiniões e sintomas psicossomáticos variados.",
    defaultLevel: "Alto",
    diseaseHistory: "Nenhum registro oficial de adoecimento até o momento.",
    existingControls: "Comunicação interna periódica.",
    probability: 3,
    severity: 4,
    uncertainty: "Certa",
    recommendation: "Desenvolver plano de cargos, carreiras e remuneração (PCCR) transparente e comunicar a saúde da empresa.",
    priority: "Alta",
    responsible: "Diretoria e Recursos Humanos",
    status: "Pendente",
    deadline: "A definir pela empresa",
    periodicity: "A definir pela empresa",
    monitoring: "Reuniões gerais trimestrais (Town Halls) sobre o desempenho institucional.",
    measureResults: "Queda na rotatividade voluntária e elevação da percepção de estabilidade.",
    actionObjective: "Promover transparência institucional e previsibilidade de desenvolvimento de carreira.",
    actionProposed: "Apresentar plano de desenvolvimento individual (PDI) e critérios de progressão profissional.",
    efficacyIndicator: "Taxa de turnover e avaliação na dimensão de Insegurança no Trabalho"
  },
  {
    id: "risk-8",
    name: "Exigências Emocionais Elevadas",
    source: "Atendimento direto a clientes hostis, mediação constante de conflitos severos, ou convívio profissional direto com dor e sofrimento humano.",
    possibleInjuries: "Fadiga de compaixão, despersonalização, embotamento afetivo temporário e estresse pós-traumático secundário.",
    defaultLevel: "Alto",
    diseaseHistory: "Nenhum registro oficial de adoecimento até o momento.",
    existingControls: "Treinamento básico de atendimento ao cliente.",
    probability: 3,
    severity: 4,
    uncertainty: "Certa",
    recommendation: "Oferecer suporte psicológico / programa de apoio ao empregado (PAE) e rotação de postos de alta tensão.",
    priority: "Alta",
    responsible: "Serviço Especializado de Segurança e Medicina do Trabalho (SESMT/RH)",
    status: "Pendente",
    deadline: "A definir pela empresa",
    periodicity: "A definir pela empresa",
    monitoring: "Acompanhamento clínico periódico e reuniões de descompressão emocional quinzenais.",
    measureResults: "Redução de crises agudas de estresse e suporte efetivo aos colaboradores de linha de frente.",
    actionObjective: "Capacitar e oferecer suporte aos colaboradores expostos a cargas emocionais intensas.",
    actionProposed: "Contratar canal confidencial de acolhimento psicológico e implementar rodízio de tarefas.",
    efficacyIndicator: "Índice de utilização do suporte psicológico e atestados médicos de ordem mental"
  },
  {
    id: "risk-9",
    name: "Falta de Previsibilidade Organizacional",
    source: "Mudanças estruturais repentinas sem comunicação prévia, reestruturações constantes de equipes sem justificativa clara.",
    possibleInjuries: "Insegurança e desconfiança na gestão, resistência crônica a mudanças, estresse psicossocial.",
    defaultLevel: "Baixo",
    diseaseHistory: "Nenhum registro oficial de adoecimento até o momento.",
    existingControls: "Comunicados via mural ou e-mail corporativo.",
    probability: 2,
    severity: 2,
    uncertainty: "Certa",
    recommendation: "Elaborar plano de gestão da mudança estruturado, informando cronogramas com antecedência.",
    priority: "Baixa",
    responsible: "Lideranças e Comunicação Interna",
    status: "Pendente",
    deadline: "A definir pela empresa",
    periodicity: "A definir pela empresa",
    monitoring: "Boletins informativos prévios antes de quaisquer modificações de rotina.",
    measureResults: "Menor índice de boatos e maior aceitação das transições operacionais.",
    actionObjective: "Aumentar a previsibilidade e a clareza sobre mudanças organizacionais.",
    actionProposed: "Estabelecer política de comunicação prévia de 30 dias para qualquer alteração de processos.",
    efficacyIndicator: "Índice de satisfação na pesquisa de clima e adesão aos novos processos"
  },
  {
    id: "risk-10",
    name: "Assédio Moral ou Condutas Ofensivas",
    source: "Humilhações públicas, boicotes informais de trabalho, piadas ofensivas recorrentes ou abuso sistemático de autoridade.",
    possibleInjuries: "Depressão grave, transtorno de estresse pós-traumático (TEPT), ideação suicida, afastamento previdenciário prolongado.",
    defaultLevel: "Grave",
    diseaseHistory: "Nenhum registro oficial de adoecimento até o momento.",
    existingControls: "Código de conduta básico da empresa.",
    probability: 2,
    severity: 5,
    uncertainty: "Certa",
    recommendation: "Instituir canal de ouvidoria/denúncias anônimo e independente com apuração rigorosa (Lei 14.457/22 - CIPA).",
    priority: "Alta",
    responsible: "Comitê de Ética, CIPA e Alta Direção",
    status: "Pendente",
    deadline: "A definir pela empresa",
    periodicity: "A definir pela empresa",
    monitoring: "Relatórios estatísticos mensais de denúncias recebidas, apuradas e sanadas.",
    measureResults: "Tolerância zero com condutas abusivas e apuração de 100% das notificações em até 15 dias.",
    actionObjective: "Eliminar e prevenir quaisquer manifestações de assédio moral ou condutas abusivas no ambiente.",
    actionProposed: "Capacitação obrigatória de 100% dos gestores e colaboradores sobre assédio, conforme NR-05 / Lei 14.457/22.",
    efficacyIndicator: "Tempo médio de resposta a denúncias na ouvidoria e taxa de conformidade nos treinamentos"
  }
];
